-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.50.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2012/8/30 0:47:04
-- Server version: 5.5.25a
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE xiong;

--
-- Definition for table ci_sessions
--
DROP TABLE IF EXISTS ci_sessions;
CREATE TABLE ci_sessions (
  session_id VARCHAR(40) NOT NULL DEFAULT '0',
  ip_address VARCHAR(16) NOT NULL DEFAULT '0',
  user_agent VARCHAR(120) NOT NULL,
  last_activity INT(10) UNSIGNED NOT NULL DEFAULT 0,
  user_data TEXT NOT NULL,
  PRIMARY KEY (session_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table department
--
DROP TABLE IF EXISTS department;
CREATE TABLE department (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '名称',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 10
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '部门';

--
-- Definition for table productTestInfo
--
DROP TABLE IF EXISTS productTestInfo;
CREATE TABLE productTestInfo (
  id INT(11) NOT NULL AUTO_INCREMENT,
  sn VARCHAR(255) NOT NULL COMMENT '序列号',
  equipmentSn VARCHAR(255) NOT NULL COMMENT '测试设备序列号',
  testTime DATETIME NOT NULL COMMENT '测试时间',
  testStation INT(11) NOT NULL COMMENT '测试站',
  tester INT(11) NOT NULL COMMENT '测试员',
  productType VARCHAR(255) NOT NULL COMMENT '产品类型',
  result TINYINT(1) NOT NULL COMMENT '测试结果',
  column1 TEXT DEFAULT NULL COMMENT '自定义项1',
  column2 TEXT DEFAULT NULL COMMENT '自定义项2',
  column3 TEXT DEFAULT NULL COMMENT '自定义项3',
  column4 TEXT DEFAULT NULL COMMENT '自定义项4',
  column5 TEXT DEFAULT NULL COMMENT '自定义项5',
  column6 TEXT DEFAULT NULL COMMENT '自定义项6',
  column7 TEXT DEFAULT NULL COMMENT '自定义项7',
  column8 TEXT DEFAULT NULL COMMENT '自定义项8',
  column9 TEXT DEFAULT NULL COMMENT '自定义项9',
  column10 TEXT DEFAULT NULL COMMENT '自定义项10',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '产品测试信息';

--
-- Definition for table productType
--
DROP TABLE IF EXISTS productType;
CREATE TABLE productType (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '名称',
  img VARCHAR(255) NOT NULL COMMENT '图纸',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '产品类型';

--
-- Definition for table productTypeTestCase
--
DROP TABLE IF EXISTS productTypeTestCase;
CREATE TABLE productTypeTestCase (
  id INT(11) NOT NULL AUTO_INCREMENT,
  productType INT(11) NOT NULL COMMENT '产品类型',
  testItem INT(11) NOT NULL COMMENT '测试项目',
  stateFile VARCHAR(255) DEFAULT NULL COMMENT '状态文件名',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '产品类新测试案例组合';

--
-- Definition for table skillLevel
--
DROP TABLE IF EXISTS skillLevel;
CREATE TABLE skillLevel (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '名称',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '技能水平';

--
-- Definition for table team
--
DROP TABLE IF EXISTS team;
CREATE TABLE team (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '名称',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '组';

--
-- Definition for table tester
--
DROP TABLE IF EXISTS tester;
CREATE TABLE tester (
  id INT(11) NOT NULL AUTO_INCREMENT,
  employeeId VARCHAR(255) NOT NULL COMMENT '员工号',
  testRight INT(11) NOT NULL COMMENT '测试权限',
  skillLevel INT(11) NOT NULL COMMENT '技能级别',
  department INT(11) NOT NULL COMMENT '所属部门',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '测试者';

--
-- Definition for table testItem
--
DROP TABLE IF EXISTS testItem;
CREATE TABLE testItem (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '名称',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '测试项目';

--
-- Definition for table testItemMarkValue
--
DROP TABLE IF EXISTS testItemMarkValue;
CREATE TABLE testItemMarkValue (
  id INT(11) NOT NULL AUTO_INCREMENT,
  testItemResult INT(11) NOT NULL COMMENT '所属测试项目结果',
  value VARCHAR(255) NOT NULL COMMENT '数值',
  markF VARCHAR(255) DEFAULT NULL COMMENT '频率标示',
  markT VARCHAR(255) DEFAULT NULL COMMENT '时间标示',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '测试项目取样值';

--
-- Definition for table testItemResult
--
DROP TABLE IF EXISTS testItemResult;
CREATE TABLE testItemResult (
  id INT(11) NOT NULL AUTO_INCREMENT,
  productTestInfo INT(11) NOT NULL COMMENT '所属产品测试信息',
  testItem INT(11) NOT NULL COMMENT '测试项目',
  img TEXT NOT NULL COMMENT '测试结果图',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '测试项目结果';

--
-- Definition for table testRight
--
DROP TABLE IF EXISTS testRight;
CREATE TABLE testRight (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '名称',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '测试权限';

--
-- Definition for table testStation
--
DROP TABLE IF EXISTS testStation;
CREATE TABLE testStation (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL COMMENT '名称',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '测试站';

--
-- Definition for table user
--
DROP TABLE IF EXISTS user;
CREATE TABLE user (
  id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL COMMENT '用户名',
  team INT(11) NOT NULL COMMENT '所属组',
  PRIMARY KEY (id),
  UNIQUE INDEX username (username)
)
ENGINE = INNODB
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 5461
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '系统用户';

-- 
-- Dumping data for table ci_sessions
--
INSERT INTO ci_sessions VALUES 
  ('ac68a585a616f34ec55df61c99f158ce', '127.0.0.1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8) AppleWebKit/536.25 (KHTML, like Gecko) Version/6.0 Safari/536.25', 1346258335, '');

-- 
-- Dumping data for table department
--
INSERT INTO department VALUES 
  (1, '部门1'),
  (3, '部门2'),
  (5, '部门3'),
  (6, '部门4');

-- 
-- Dumping data for table productTestInfo
--
INSERT INTO productTestInfo VALUES 
  (1, '1', '1', '2012-08-30 00:06:20', 1, 1, '1', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- 
-- Dumping data for table productType
--
INSERT INTO productType VALUES 
  (1, '产品类型1', 'ada96-change_log.txt'),
  (2, 'p2', 'f3830-license-gpl3.txt');

-- 
-- Dumping data for table productTypeTestCase
--
INSERT INTO productTypeTestCase VALUES 
  (1, 1, 1, 'state1');

-- 
-- Dumping data for table skillLevel
--
INSERT INTO skillLevel VALUES 
  (1, '级别1');

-- 
-- Dumping data for table team
--
INSERT INTO team VALUES 
  (1, '组1');

-- 
-- Dumping data for table tester
--
INSERT INTO tester VALUES 
  (1, '001', 1, 1, 1);

-- 
-- Dumping data for table testItem
--
INSERT INTO testItem VALUES 
  (1, '测试项目1');

-- 
-- Dumping data for table testItemMarkValue
--
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table testItemResult
--
INSERT INTO testItemResult VALUES 
  (1, 1, 1, '<p>\n\taa</p>\n');

-- 
-- Dumping data for table testRight
--
INSERT INTO testRight VALUES 
  (1, '组长');

-- 
-- Dumping data for table testStation
--
INSERT INTO testStation VALUES 
  (1, '测试站点1');

-- 
-- Dumping data for table user
--
INSERT INTO user VALUES 
  (1, 'user01', 1),
  (2, 'user02', 1),
  (3, 'user03', 1);

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;